import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {FaRegUserCircle} from "react-icons/fa";
import {Suspense} from "react";
import Loading from "@/app/loading";


interface NavBarProps {
    text: string;
    link: string;
}

const NavBarElement = ({text, link}: NavBarProps) => {
    return (<div className={"text-gray-800 bg-orange-400 p-2 rounded-xl hover:bg-orange-300 shadow-md flex justify-center items-center"}><Link href={link}>{text}</Link></div>)
}

function NavBar() {
    return (
        <>
            <div className={"w-full bg-gray-400 p-4 border-gray-300 border-4 rounded-xl"}>
                <div className={"flex justify-between"}>
                    <div className={"flex space-x-4 text-2xl cursor-pointer"}>
                        <div className={"pt-2"}>My List Maker: BEYOND</div>
                        <NavBarElement text={"Home"} link={"/"}/>
                        <NavBarElement text={"Create List"} link={"/CreateList"} />
                        <NavBarElement text={"View List"} link={"/ShareList"}/>
                    </div>
                    <div>
                        <FaRegUserCircle size={48} className={"w-full h-full text-orange-400 hover:text-orange-300"}/>
                    </div>
                </div>

            </div>
        </>
    )
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <Suspense fallback={<Loading />}>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <NavBar />
        {children}
        </body>
    </Suspense>
    </html>
  );
}
